### ISSUE TITLE
请问目前常用的服务器挖矿效率怎么样？

### ISSUE THREAD

**Issue by bitcard** [CoinSummer/filecoin#1]
目前常用的服务器，1是gpu很差，2是硬盘大多为传统机械硬盘，这些机器挖矿的效率怎么样？谢谢！

**Comment by NewMai** [comment]
有问题请在群内交流，
![image](https://user-images.githubusercontent.com/9707303/85570683-2280b080-b666-11ea-84d8-f3007d252960.png)
